name: Implementación Completa

on:
  push:
    branches: [ main ]

jobs:
  # Checkout Repositories (Job 1)
  checkout-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Checkout Frontend Repository
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Checkout Devlake Repository (Optional)  # Update if Devlake is in a separate repo
        uses: actions/checkout@v3
        with:
          repository: your-devlake-repository  # Replace with your Devlake repo URL (if separate)
          path: devlake  # Adjust path if needed

  # Build Backend (Job 2)
  build-backend:
    runs-on: ubuntu-latest
    needs: checkout-repos  # Wait for repositories to checkout
    steps:
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          path: backend

      - name: Install Backend Dependencies
        run: npm install
        working-directory: backend

      - name: Build Backend
        run: npm run build
        working-directory: backend

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: ./dist
          working-directory: backend

  # Build Frontend (Job 3)
  build-frontend:
    runs-on: ubuntu-latest
    needs: checkout-repos  # Wait for repositories to checkout
    needs: build-backend  # Wait for backend to build first
    steps:
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          path: frontend

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend

      - name: Build Frontend
        run: ng build --prod
        working-directory: frontend

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-artifact
          path: ./dist
          working-directory: frontend

  # Build Devlake (Job 4)
  build-devlake:
    runs-on: ubuntu-latest
    needs: checkout-repos  # Wait for repositories to checkout
    needs: [build-backend, build-frontend]  # Wait for both backend and frontend to build
    steps:
      - name: Build Devlake (use existing checkout if in same repo)
        run: go build -o devlake ./cmd/devlake  # Adjust path if Devlake is in separate repo
        working-directory: devlake  # Adjust path if Devlake is in separate repo

  # Deploy Backend (Job 5)
  deploy-backend:
    runs-on: ubuntu-latest
    needs: [checkout-repos, build-backend]  # Wait for repositories to checkout and backend build
    steps:
      - name: Download Backend Artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-artifact
          path: ./dist

      - name: Login to Azure
        uses: azure/login@v3
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend to Azure Functions
        uses: azure/functions-deploy@v2
        with:
          app-name: your-azure-function-app-name
          app-type: http
          publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}
          files: ./dist

  # Deploy Frontend (Job 6)
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [checkout-repos, build-frontend]  # Wait for repositories to checkout and frontend build
    steps:
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-artifact
          path: ./dist

      - name: Login to Azure
        uses: azure/login@v3
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Frontend to Azure Blob Storage
        uses: azure/cli@v
